### ISSUE TITLE
[BUG] Delete lines on execute

### ISSUE THREAD

**Issue by MypowerHD** [FrankR85/cobol-workspace#3]
Servus, im Auftrag einer Freundin erstelle ich diese Issue.
Sie trat mit dem Problem heran, dass sie Ihr Image nicht installieren konnte. Nach mehrstündigem Suchen ihrer und meinerseits sind wir nun an dem Punkt, dass wir Docker sowie alles Nötige installiert und die Windows Benachrichtigungseinstellungen geändert haben, welche unser erstes Problem darstellten, da Docker im Verbund mit Deaktivierung dieser Einstellungen nicht das Sharing durchbringen konnte.  

Nun sind wir aber an der Stelle angekommen (Punkt 4), dass wir das Test-Programm ausführen können. Bei mir wird alles korrekt ausgeführt aber bei ihr nicht, evtl. haben Sie ein paar Ratschläge, welche uns helfen können.

Problembeschreibung:
Nach Ausführung des Befehls "cd ttt && ./run-ut.sh" bekommen wir bei ihr folgenden Output:
![Hur4tau3QRazqrjloKL7lw](https://user-images.githubusercontent.com/10728025/93726585-2cf40d00-fbb7-11ea-99ad-f4e7667caa74.png)

Zudem werden bei ihr aus der Datei "ttt/test/TESTPRG.CBL" Abschnitte/Codezeilen durch das Ausführen des Befehls gelöscht.
![tEmVyWbSSUuM9FJxUx2VOQ](https://user-images.githubusercontent.com/10728025/93726679-b3105380-fbb7-11ea-9eb7-7701a6a467ca.png)
Dies passiert auch bei den anderen Testprogrammen.

Hier noch einmal der vollständige diff vom GIT-Clienten.
```diff
@@ -36,163 +36,14 @@
       * Indices
        01 IX.
          02 IX-Y PIC 9.
        PROCEDURE DIVISION.
            PERFORM UT-INITIALIZE
-
-           DISPLAY SPACE
-           DISPLAY "TEST SUITE:"
-           DISPLAY
-           'TIC TACT TOE TEST'
-           DISPLAY SPACE
-
-           MOVE 'Gewinnt waagerecht'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'X' TO FELD(1,1)
-                       FELD(1,2)
-           SET AKTIVER-SPIELER-X TO TRUE
-           MOVE '3,1' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM PRUEFE-SPIELSTATUS
-           PERFORM DISPLAY-SPIELFELD
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'Sieg'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'Gewinnt senkrecht'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'X' TO FELD(1,1)
-                       FELD(2,1)
-           SET AKTIVER-SPIELER-X TO TRUE
-           MOVE '1,3' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM PRUEFE-SPIELSTATUS
-           PERFORM DISPLAY-SPIELFELD
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'Sieg'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'Gewinnt diagonal'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'X' TO FELD(1,1)
-                       FELD(2,2)
-           SET AKTIVER-SPIELER-X TO TRUE
-           MOVE '3,3' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM PRUEFE-SPIELSTATUS
-           PERFORM DISPLAY-SPIELFELD
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'Sieg'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'Normaler Zug mit Spielerwechsel'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE '3,3' TO EINGABE
-           SET AKTIVER-SPIELER-X TO TRUE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM PRUEFE-SPIELSTATUS
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'Laufend'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE AKTIVER-SPIELER TO UT-ACTUAL
-           MOVE 'O'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'Alle Felder belegt'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'XOXXOXOX' TO SPIELFELD
-           MOVE 8 TO ZUG
-           SET AKTIVER-SPIELER-O TO TRUE
-           MOVE '3,3' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM PRUEFE-SPIELSTATUS
-           PERFORM DISPLAY-SPIELFELD
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'Unentschieden'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'Feld schon belegt'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'X' TO FELD(2,1)
-           MOVE '1,2' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           PERFORM DISPLAY-SPIELFELD
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'FEHLER: UngÃ¼ltige Eingabe'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'AuÃŸerhalb des Spielfeldes'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE '5,7' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'FEHLER: UngÃ¼ltige Eingabe'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
-
-           PERFORM UT-AFTER
-           MOVE 'UngÃ¼ltige Eingabe'
-               TO UT-TEST-CASE-NAME
-           PERFORM UT-BEFORE
-           MOVE 'a,b' TO EINGABE
-           PERFORM PRUEFE-LESE-EINGABE
-           ADD 1 TO UT-TEST-CASE-COUNT
-           SET UT-NORMAL-COMPARE TO TRUE
-           MOVE SPIEL-STATUS TO UT-ACTUAL
-           MOVE 'FEHLER: UngÃ¼ltige Eingabe'
-                       TO UT-EXPECTED
-           SET UT-COMPARE-DEFAULT TO TRUE
-           PERFORM UT-ASSERT-EQUAL
            PERFORM UT-AFTER
             COPY ZUTZCPD     .
            .
        UT-BEFORE.
-             PERFORM INIT
 
            .
        UT-AFTER.
```

Ich kann mir das Vorgehen des Programmes nicht erklären, da bei mir alles wunderbar und sauber durchläuft. Desweiteren werden bei mir keinerlei Codechanges durch das Programm durchgeführt.

Die Repo von ihr erreichen sie hier: [Link zur Repo](https://github.com/MypowerHD/cobol-workspace-bug-report)
Betriebssystem ist Windows 10 Pro.

**Comment by MypowerHD** [comment]
Ein kleines Update zur Thematik; wir haben einfach mal den Befehl aus dem Bash-Script direkt in der Console ausgeführt und siehe da, das Programm funktioniert einwandfrei, evtl. hilft das ja beim Finden des Problems.
![FbJon9oXQ8aJMYUU4-1GTg](https://user-images.githubusercontent.com/10728025/93729137-7f3b2b00-fbc3-11ea-964f-d49d05969ca2.png)

**Comment by FrankR85** [comment]
Vielen Dank für die ausführliche Bug-Beschreibung! 👍 

Die Diffs sind erklärbar: Das Testframework funktioniert so, dass es das Original-Programm und die Datei mit den Testfällen zusammenfügt und ein `TESTPRG.CBL` erstellt. Dieses `TESTPRG.CBL` wird anschließend gestartet und führt dann die Testfälle durch, errechnet die Statistik und gibt diese auf der Konsole aus.
Die Fehlermeldung besagt jetzt ```FILE UTESTS NOT FOUND```, also die Datei mit den Testfällen fehlt ihm irgendwie. Dadurch ist das zusammengefügte `TESTPGM.CBL` auch leer.

Korrekterweise hätten wir das `TESTPGM.CBL` auch gar nicht committen sollen, da es generierter Code ist und - wie man sieht - so nur Verwirrung stiftet.

Die Frage ist also, warum findet er die Datei `ttt\test\TTTT.CBL` nicht, wenn du das Skript `run-ut.sh` ausführst, aber wohl, wenn du den Befehl daraus direkt ausführst. Eigentlich müsste dieser Befehl global ausführbar sein, d.h. unabhängig vom aktuellen `$(pwd)`.
Sehr seltsam. Ich tippe auf ein Windows-Phänomen, kann das aber zunächst nicht nachstellen, weil ich gerade keinen Windows-Rechner zur Hand habe.
@LeonWest95 Hast du eine Idee?

Auf jeden Fall sieht euer Setup für den Kurs schon sehr gut aus! Das Skript zum Ausführen der Testfälle braucht ihr auch gar nicht unbedingt. Wichtig ist, dass Docker läuft und die mounts funktionieren und das habt ihr ja geschafft! 👍 

Falls ihr bei eurem mehrstündigen Installationsprozess über Probleme gestolpert seid, deren Lösung auch für die anderen Kursteilnehmer wichtig sein könnte, wäre es super, wenn ihr die irgendwo aufschreiben könntet (gerne als PR hier). Denn weder Leon noch ich haben ein Windows 10 Pro zum Ausprobieren.

**Comment by MypowerHD** [comment]
Moin Moin,

> Die Diffs sind erklärbar: Das Testframework funktioniert so, dass es das Original-Programm und die Datei mit den Testfällen zusammenfügt und ein `TESTPRG.CBL` erstellt. Dieses `TESTPRG.CBL` wird anschließend gestartet und führt dann die Testfälle durch, errechnet die Statistik und gibt diese auf der Konsole aus.

ok dann weiß ich bescheid^^.

> Die Frage ist also, warum findet er die Datei `ttt\test\TTTT.CBL` nicht, wenn du das Skript `run-ut.sh` ausführst, aber wohl, wenn du den Befehl daraus direkt ausführst. Eigentlich müsste dieser Befehl global ausführbar sein, d.h. unabhängig vom aktuellen `$(pwd)`.
> Sehr seltsam. Ich tippe auf ein Windows-Phänomen, kann das aber zunächst nicht nachstellen, weil ich gerade keinen Windows-Rechner zur Hand habe.

Ich tippe auch auf ein Windows-Phänomen, da bei mir alles wunderbar und prima klappt nur bei ihr eben nicht, was ich mir nur durch Windows erklären kann, Ich versuche mal nachehr den Docker Cache bei ihr zu clearen.   

> Falls ihr bei eurem mehrstündigen Installationsprozess über Probleme gestolpert seid, deren Lösung auch für die anderen Kursteilnehmer wichtig sein könnte, wäre es super, wenn ihr die irgendwo aufschreiben könntet (gerne als PR hier). Denn weder Leon noch ich haben ein Windows 10 Pro zum Ausprobieren.

Wie gesagt dass einzige große Problem war dass Docker ne Unhandled Exception geschmissen hat wenn die Benachrichtigungs einstellungen Deaktiviert(Gemuted) sind, zudem Problem werde ich bei Docker auch noch eine Issue erstellen müssen hatte bis eben aber dafür noch keine Zeit gefunden.

Problem Lösung:
"[Windows] + [I]" => System => Benachrichtigungsassitent =>Unter "Automatische Regeln" => Radikal alles auf aus.
Sowie im Select drüber auf Aus Gestellt.

**Comment by LeonWest95** [comment]
Hallo zusammen.
Ich habe einmal versucht, den Fehler auf einem Windows-Rechner nachzustellen.
Leider läuft das Programm aus dem verlinkten Git-Repository sowohl auf meiner Linux-, als auch auf meiner Windows-Maschine fehlerfrei.  

Mir ist aber aufgefallen, dass unter cmd der Docker run Befehl nicht läuft, weil Windows $pwd nicht kennt. Der folgende Befehl sollte unter cmd laufen:

docker run -it --mount src=%cd%,target=/root/cobol,type=bind frankr85/cobol:latest bash

Ich greife hier zwar nach Strohhalmen, aber welche Konsole habt ihr verwendet?

**Comment by MypowerHD** [comment]
Wir haben alles durch(cmd/powershell/gitbash(MING64W)), ich hab dass problem auf keiner einzelnen Konsole, nur bei ihr welches ich mir nicht erklären kann.

**Comment by MypowerHD** [comment]
und dass docker nicht vernünftig mounten kann, lag an den Benachrichtigungseinstellungen. Hab vorhin auch mal mein Homelab dafür missbraucht auf dem Läuft auch alles sauber durch 👍

**Comment by FrankR85** [comment]
Alles klar, danke euch für die detaillierten Informationen!

Ich schließe den Issue mal, denn so wie ich das sehe, müssten tatsächlich 2 weitere Bugs erstellt werden: Einer bei Docker und einer bei Windows. 🐵
